services:
  postgres:
    image: postgres
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
  server:
    build: .
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    depends_on:
      - postgres
