services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
  server:
    build: .
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - PYTHONPYCACHEPREFIX
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    depends_on:
      - postgres
