#!/bin/bash

ROOT="$(git rev-parse --show-toplevel)"

# Prevent commit to master branch.
branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "${branch}" = "master" ]; then
  echo "master branch is protected from new commits."
  exit 1
fi

# Run pylint.
echo "Running pylint ..."
pylint "${ROOT}/server"
