#!/bin/bash

ROOT="$(git rev-parse --show-toplevel)"

# Prevent commit to master branch.
branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "${branch}" = "master" ]; then
  echo "master branch is protected from new commits."
  exit 1
fi

commit_py_files="$(git diff --name-only --cached | grep "\.py$")"
if [[ ! -z "${commit_py_files}" ]]; then
  # Run black.
  echo "Running black ..."
  black "${commit_py_files}"

  # Run pylint.
  echo "Running pylint ..."
  pylint "${commit_py_files}"
fi

